source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-paginate"
gem "erb"

# stdlib gems no longer bundled with Ruby 3.4+ (needed by jekyll 3.9)
gem "csv"
gem "base64"
gem "bigdecimal"
gem "logger"
gem "webrick"
